Задание №2 - Перемещение заданий в workspace и потокобезопасный массив.
xdrond/FocusStartHomeworks pull request #2
Opened 2020-10-27 10:43 UTC by xdrond

Перенёс предыдущее задание и новое(второе) в один workspace. В массиве не реализовал проверку с индексами, так как опирался на стандартный массив, который делегирует эту задачу выше, если это требовалось - допишу. Доступ к массиву реализуется посредством выстраивания в очередь запросов к массиву, таким образом обращения из потоков других будут обработаны в том порядке, в котором поступили. Мне кажется это не очень хорошим решением, но к сожалению я пока не знаю, как это исправить. Подсчёт количества элементов я пытался реализовать с помощью помещения тестовых параллельных задач в DispatchGroup и подсчёта из notify(), но почему-то это не сработало и поэтому в main.swift осталась строчка с sleep().

2020-10-28 19:34 UTC, korshunigor commented
Принято на проверку

2020-11-16 13:10 UTC, Viscount88 requested changes

2020-11-16 13:10 UTC, Viscount88 commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		get { return self.array.isEmpty }
Получается тут лучше вообще все операции в этой очереди делать, чтобы все операции, связанные с элементами происходили внутри его собственной очереди.

2020-11-16 13:10 UTC, Viscount88 commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		let element = self.array[index]
Проверка логичная, только во-первых она должна быть внутри очереди, иначе может получиться, что в момент проверки он есть, а в момент удаления - уже нет. А во-вторых, я бы еще использовал барьер для очереди этого массива.

2020-11-16 13:10 UTC, Viscount88 commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		get { return self.array[index] }
Оба действия делаются внутри очереди и делаются синхронно. Причем на сете стоит еще барьер заюзать.

2020-11-16 13:10 UTC, Viscount88 commented on ThreadSafeArray/ThreadSafeArray/main.swift
> +for _ in 0...1{
зачем эти циклы внутри циклов? Выглядеть должно примерно так: 
let dispathGroup = DispatchGroup()
let arrayMainSafe = ThreadSafeArray<String>()
let queue = DispatchQueue.global(qos: .userInteractive)

dispathGroup.enter()
queue.async {
            for number in 0...1000 {
                arrayMainSafe.append(element)
            }
            dispathGroup.leave()
        }

Повторяшь ещё раз по заданию, затем: 

        dispathGroup.wait()
И делаешь вывод результата.

2020-11-16 17:17 UTC, xdrond commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		get { return self.array[index] }
Можете, пожалуйста, пояснить, почему вызывающий поток должен ожидать синхронно при выполнении set?
А барьер, если я правильно понимаю, нужен для параллельной очереди, в данном случае очередь последовательная и set сработает только после выполнения стоящих в очереди задач перед ним. Сейчас я исправил в новом коммите в соответствии с последовательной очередью, но без барьера.

2020-11-17 05:12 UTC, xdrond commented
Исправил локально конфликт слияния из-за созданного workspace в разных ветках.

2020-11-17 05:26 UTC, merged

2020-11-24 09:46 UTC, Viscount88 commented on ThreadSafeArray/ThreadSafeArray/ThreadSafeArray.swift
> +		get { return self.array[index] }
Потому что при асинхронном может оказаться так, что ты это сделаешь одновременно например с удалением элемента из массива, или с еще одним изменением этого элемента из другого места. И там порядок действий при асинхронном будет определяться свободными ресурсами, проще говоря рандомом, можно на ровно месте неконсистентную фигню получить, или того хуже краш. Конечно это всё чисто в теории, но как показывает практика - если где-то можно облажаться - так оно и будет, вопрос времени.